### ISSUE TITLE
Tester sur du vrai materiel

### ISSUE THREAD

**Issue by Lingelo** [flozz/gameboy-examples#2]
Hello, 
Superbe série de tuto vraiment cool. 
J'aimerais savoir comment tu testes tout cela sur une vraie GB ou GBC ? 
Merci

**Comment by flozz** [comment]
Bonjour,

je réponds même si l'issue est fermée (des fois que des gens tombent dessus)

### Il existe des cartouches qui permettent de charger des ROM depuis une carte SD :  

* **Everdrive GB :** https://krikzz.com/store/home/47-everdrive-gb.html
  Il en existe 3 modèles : X3, X5 et X7, plus ou moins perfectionnés (et plus ou moins chers). Je recommanderais de prendre au moins le X5 (le gros défaut du X3 est sa gestion des sauvegardes qui nécessite d'appuyer sur un bouton pour *soft reset* la console avant de l'éteindre si on ne veut pas perdre sa sauvegarde)

* **EZ-Flash Junior :** https://www.ezflash.cn/product/ezflash-junior/
  À priori moins cher que l'Everdrive mais ne l'ayant pas testé je ne sais pas c'il vaut :)

### La seconde solution c'est de flasher des cartouches spécialement conçus pour ça (Flash Cart) à l'aide d'un linker.

* Pour le linker, je recommande le **GBxCart RW** de InsideGadgets qui a un bon rapport qualité prix : https://shop.insidegadgets.com/product/gbxcart-rw/

* Et pour les Flash Cart, on en trouve également chez InsideGadgets, lire cette page pour s'y retrouver parmi leurs références : https://shop.insidegadgets.com/choosing-a-flash-cart/

* Et il y a aussi de bonnes Flash Cart chez Catskull pour les cartouches de 32k :  https://catskullelectronics.com/collections/game-boy/products/32k-gameboy-flash-cart

* Dernière solution : les jeux contrefaits que l'on trouve chez AliExpress sont généralement flashable (par contre la qualité des cartouches est très mauvaise).
