### ISSUE TITLE
problem with color

### ISSUE THREAD

**Issue by jackygoule** [flozz/gameboy-examples#3]
Hello i try to convert image.png for use in my rom.gb.
The conversion is a succes except ,a color is lack.
I read article about palette .
But i don't fond the way to have 4 colors of gameboy.
My image.png work with gb-studio.
thanks

**Comment by flozz** [comment]
Hello,

[img2gb](https://github.com/flozz/img2gb) currently rely on the color's luminosity to choose if it should be converted as color 0, 1, 2 or 3 of the GB palette. So it is possible that two of the colors of your image are in the same luminosity range and are converted as the same color.

This behavior was ok to fit my needs, but it would be an improvement to handle things differently when an image only contains 4 colors.

:)

**Comment by jackygoule** [comment]
Thanks for your answer.
I try to use plugins gimp-tilemap-gb and i have a similar problems with .When i try to convert the .png the plugin say to me that the .png have 5 colors .I use the placeholder file i find in the asset of gb-studio for draw with gimp.I see only 4 colors.
I close the issue ?

**Comment by flozz** [comment]
Yes yo can close this issue, but you may open an other one on img2gb: I may improve it if I am able to find some time. If you do so, please include the image to the issue, that would help me :)

**Comment by jackygoule** [comment]
link for image:
https://ibb.co/2KyC5Yw
i use this file to draw:
https://ibb.co/7pHxyZp
